version: '3.2'

services:

    loan-db:
        image: mariadb
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
        environment:
          MYSQL_DATABASE: loan_db
          MYSQL_ROOT_PASSWORD: loan-db
          MYSQL_USER: loan-db
          MYSQL_PASSWORD: loan-db
        expose:
          - "3306"
        ports:
          - target: 3306
            published: 13306
            protocol: tcp
            mode: host